#!/usr/bin/env bash
# Ensure the iOS Info.plist carries the privacy usage strings the app needs.
#
# Why this exists: iOS terminates an app that touches location or motion without
# a usage description, and Smooth AF does both (GPS track + accelerometer
# scoring). Those strings live in ios/App/App/Info.plist, which is generated by
# `npx cap add ios` and is NOT in git — so any fresh clone or regenerated ios/
# would silently lose them and the app would crash on Start Drive.
#
# Runs automatically after `cap sync ios` (see package.json). Idempotent, and a
# no-op when there's no iOS project (CI, web-only checkouts, non-Mac).
set -euo pipefail

PLIST="ios/App/App/Info.plist"
PB="/usr/libexec/PlistBuddy"

# No iOS project or not on macOS — nothing to do, and that's fine.
[ -f "$PLIST" ] || { echo "[ios-privacy] no $PLIST — skipping"; exit 0; }
[ -x "$PB" ]     || { echo "[ios-privacy] PlistBuddy unavailable — skipping"; exit 0; }

set_string(){
  local key="$1" value="$2"
  # Delete-then-add so re-runs update the text rather than erroring on a dup.
  "$PB" -c "Delete :$key" "$PLIST" >/dev/null 2>&1 || true
  "$PB" -c "Add :$key string $value" "$PLIST"
  echo "[ios-privacy] set $key"
}

set_string NSLocationWhenInUseUsageDescription \
  "Smooth AF uses your location to score your drive and track your route."
set_string NSMotionUsageDescription \
  "Smooth AF uses motion sensors to measure how smoothly you accelerate, brake, and corner."

# Export compliance. Without this App Store Connect asks "does your app use
# encryption?" on EVERY upload and holds the build back from testers until it's
# answered by hand — which would defund the whole point of automatic builds.
# The app only uses standard HTTPS, which is exempt.
"$PB" -c "Delete :ITSAppUsesNonExemptEncryption" "$PLIST" >/dev/null 2>&1 || true
"$PB" -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST"
echo "[ios-privacy] set ITSAppUsesNonExemptEncryption=false (export compliance)"
