#!/usr/bin/env bash
# Ensure the iOS Info.plist carries the privacy usage strings the app needs.
#
# Why this exists: iOS terminates an app that touches location or motion without
# a usage description, and Smooth AF does both (GPS track + accelerometer
# scoring). Those strings live in ios/App/App/Info.plist, which is generated by
# `npx cap add ios` and is NOT in git — so any fresh clone or regenerated ios/
# would silently lose them and the app would crash on Start Drive.
#
# Runs automatically after `cap sync ios` (see package.json). Idempotent, and a
# no-op when there's no iOS project (CI, web-only checkouts, non-Mac).
set -euo pipefail

PLIST="ios/App/App/Info.plist"
PB="/usr/libexec/PlistBuddy"

# No iOS project or not on macOS — nothing to do, and that's fine.
[ -f "$PLIST" ] || { echo "[ios-privacy] no $PLIST — skipping"; exit 0; }
[ -x "$PB" ]     || { echo "[ios-privacy] PlistBuddy unavailable — skipping"; exit 0; }

set_string(){
  local key="$1" value="$2"
  # Delete-then-add so re-runs update the text rather than erroring on a dup.
  "$PB" -c "Delete :$key" "$PLIST" >/dev/null 2>&1 || true
  "$PB" -c "Add :$key string $value" "$PLIST"
  echo "[ios-privacy] set $key"
}

set_string NSLocationWhenInUseUsageDescription \
  "Smooth AF uses your location to score your drive and track your route."
# Always-location: required for background drive recording. Without it the GPS
# watch dies the moment the app is backgrounded (screen off / in Maps), and the
# drive comes back as a sparse straight line with an unreliable score.
set_string NSLocationAlwaysAndWhenInUseUsageDescription \
  "Smooth AF keeps tracking your drive in the background so your route and score stay accurate even with the screen off or while you're navigating in Maps."
set_string NSMotionUsageDescription \
  "Smooth AF uses motion sensors to measure how smoothly you accelerate, brake, and corner."

# Background mode: the "location" capability lets iOS keep delivering GPS fixes
# while the app is backgrounded during a drive. UIBackgroundModes is an ARRAY,
# so rebuild it cleanly (delete → add array → add the one entry).
"$PB" -c "Delete :UIBackgroundModes" "$PLIST" >/dev/null 2>&1 || true
"$PB" -c "Add :UIBackgroundModes array" "$PLIST"
"$PB" -c "Add :UIBackgroundModes:0 string location" "$PLIST"
echo "[ios-privacy] set UIBackgroundModes=[location]"

# Bluetooth: the OBD-II dongle. iOS kills the app on first CoreBluetooth call
# without this string, exactly like location and motion above.
set_string NSBluetoothAlwaysUsageDescription \
  "Smooth AF connects to your OBD-II adapter to read throttle, RPM, and true vehicle speed from the car."
set_string NSBluetoothPeripheralUsageDescription \
  "Smooth AF connects to your OBD-II adapter to read throttle, RPM, and true vehicle speed from the car."

# Export compliance. Without this App Store Connect asks "does your app use
# encryption?" on EVERY upload and holds the build back from testers until it's
# answered by hand — which would defund the whole point of automatic builds.
# The app only uses standard HTTPS, which is exempt.
"$PB" -c "Delete :ITSAppUsesNonExemptEncryption" "$PLIST" >/dev/null 2>&1 || true
"$PB" -c "Add :ITSAppUsesNonExemptEncryption bool false" "$PLIST"
echo "[ios-privacy] set ITSAppUsesNonExemptEncryption=false (export compliance)"

# Spotify sign-in returns to the app through a custom URL scheme (appUrlOpen).
"$PB" -c "Delete :CFBundleURLTypes" "$PLIST" >/dev/null 2>&1 || true
"$PB" -c "Add :CFBundleURLTypes array" "$PLIST"
"$PB" -c "Add :CFBundleURLTypes:0 dict" "$PLIST"
"$PB" -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes array" "$PLIST"
"$PB" -c "Add :CFBundleURLTypes:0:CFBundleURLSchemes:0 string com.smoothafdriving.app" "$PLIST"
echo "[ios-privacy] set CFBundleURLTypes (Spotify return scheme)"
